{
 "title": "Gitpod / Overview",
 "tags": [ "gitpod-mixin" ],
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   {
    "name": "cluster",
    "label": "cluster",
    "query": {
     "query": "label_values(gitpod_ws_manager_workspace_phase_total, cluster)"
    }
   },
   { "name": "datasource", "query": "prometheus" }
  ]
 },
 "panels": [
  {
   "title": "$cluster: Total Workspaces",
   "type": "graph",
   "gridPos": { "h": 11, "w": 12, "x": 0, "y": 0 },
   "repeat": "cluster",
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(gitpod_ws_manager_workspace_phase_total{cluster=~\"$cluster\", phase=\"RUNNING\"}) by (type)",
     "legendFormat": "{{ type }}"
    },
    {
     "expr": "sum(gitpod_ws_manager_workspace_activity_total{cluster=~\"$cluster\",active=\"false\"})",
     "legendFormat": "Regular Not Active"
    }
   ]
  },
  {
   "title": "$cluster: Workspace Startup Time",
   "type": "heatmap",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 11 },
   "repeat": "cluster",
   "targets": [
    {
     "expr": "histogram_quantile(0.95, rate(gitpod_ws_manager_workspace_startup_seconds_bucket{cluster=~\"$cluster\",type=\"REGULAR\"}[2m]))",
     "legendFormat": "{{ le }}"
    }
   ]
  },
  {
   "title": "$cluster: Regular Workspaces Phases",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 20 },
   "repeat": "cluster",
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by (phase) ( gitpod_ws_manager_workspace_phase_total{cluster=~\"$cluster\",phase!=\"RUNNING\"})",
     "legendFormat": "{{phase}}"
    },
    {
     "expr": "sum(rate(gitpod_ws_manager_workspace_starts_total{cluster=~\"$cluster\", type=\"REGULAR\"}[1m])) by (cluster)",
     "legendFormat": "Regular Workspace Start Requests"
    },
    {
     "expr": "sum(rate(gitpod_ws_manager_workspace_stops_total{cluster=~\"$cluster\", reason=\"failed\"}[1m])) by (cluster)",
     "legendFormat": "Total Workspace Failure Rate"
    }
   ]
  },
  {
   "title": "$cluster: # of nodes",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 28 },
   "repeat": "cluster",
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "count(node_uname_info{instance=~\".*workspace-pool.*\"}) by (cluster)",
     "legendFormat": "Workspace Nodes"
    },
    {
     "expr": "count(node_uname_info{instance=~\".*meta-pool.*\"}) by (cluster)",
     "legendFormat": "Meta Nodes"
    }
   ]
  }
 ]
}