{
 "title": "Gitpod / Component / ws-scheduler",
 "tags": [ "gitpod-mixin" ],
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   {
    "name": "cluster",
    "label": "Cluster",
    "query": {
     "query": "label_values(up{job=\"ws-scheduler\"}, cluster)"
    }
   },
   {
    "name": "node",
    "label": "Node",
    "query": {
     "query": "label_values(container_cpu_usage_seconds_total{cluster=~\"$cluster\", pod=~\"ws-scheduler.*\"}, node)"
    }
   },
   {
    "name": "pod",
    "label": "Pod",
    "query": {
     "query": "label_values(container_cpu_usage_seconds_total{cluster=~\"$cluster\", node=~\"$node\", pod=~\"ws-scheduler.*\"}, pod)"
    }
   },
   { "name": "datasource", "query": "prometheus" }
  ]
 },
 "panels": [
  {
   "title": "ws-scheduler Metrics",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "collapsed": true,
   "panels": [
    {
     "title": "Schedule attempt rate",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 1 },
     "yaxes": [
      { "format": "ops" }
     ],
     "targets": [
      {
       "expr": "sum(rate(gitpod_ws_scheduler_schedule_attempts_total[5m])) by (cluster, pod, workspaceType)",
       "legendFormat": "{{cluster}} - {{pod}} - {{workspaceType}}"
      }
     ]
    },
    {
     "title": "Schedule failure rate",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 1 },
     "yaxes": [
      { "format": "ops" }
     ],
     "targets": [
      {
       "expr": "sum(rate(gitpod_ws_scheduler_schedule_attempts_total{cluster=~\"$cluster\", result!=\"scheduled\"}[5m])) by (cluster, pod, workspaceType, result)",
       "legendFormat": "{{cluster}} - {{pod}} - {{workspaceType}} - {{result}}"
      }
     ]
    },
    {
     "title": "Preemption attempt rate",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 9 },
     "yaxes": [
      { "format": "ops" }
     ],
     "targets": [
      {
       "expr": "sum(rate(gitpod_ws_scheduler_preemption_attempts_total[5m])) by (cluster, pod)",
       "legendFormat": "{{cluster}} - {{pod}}"
      }
     ]
    },
    {
     "title": "Pending pods per queue",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 9 },
     "yaxes": [
      { "format": "pods" }
     ],
     "targets": [
      {
       "expr": "sum(gitpod_ws_scheduler_pending_pods{cluster=~\"$cluster\"}) by (cluster, queue)",
       "legendFormat": "{{cluster}} - {{queue}}"
      }
     ]
    },
    {
     "title": "Attempts until succesful scheduling - Regular workspaces",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 17 },
     "yaxes": [
      { "format": "attempts" }
     ],
     "targets": [
      {
       "expr": "histogram_quantile(0.99, \n  sum(\n    rate(gitpod_ws_scheduler_pod_scheduling_attempts_bucket{cluster=~\"$cluster\", workspaceType=\"regular\"}[5m])\n  ) by (cluster, workspaceType, le)\n)",
       "legendFormat": "{{cluster}} - 99th percentile"
      },
      {
       "expr": "histogram_quantile(0.95, \n  sum(\n    rate(gitpod_ws_scheduler_pod_scheduling_attempts_bucket{cluster=~\"$cluster\", workspaceType=\"regular\"}[5m])\n  ) by (cluster, workspaceType, le)\n)",
       "legendFormat": "{{cluster}} - 95th percentile"
      },
      {
       "expr": "histogram_quantile(0.50, \n  sum(\n    rate(gitpod_ws_scheduler_pod_scheduling_attempts_bucket{cluster=~\"$cluster\", workspaceType=\"regular\"}[5m])\n  ) by (cluster, workspaceType, le)\n)",
       "legendFormat": "{{cluster}} - 50th percentile"
      },
      {
       "expr": "  sum(\n    rate(gitpod_ws_scheduler_pod_scheduling_attempts_bucket{cluster=~\"$cluster\",workspaceType=\"regular\"}[5m])\n  ) by (cluster)\n  /\n    sum(\n    rate(gitpod_ws_scheduler_pod_scheduling_attempts_bucket{cluster=~\"$cluster\",workspaceType=\"regular\"}[5m])\n  ) by (cluster)",
       "legendFormat": "{{cluster}} - avg"
      }
     ]
    },
    {
     "title": "End-to-end scheduling duration - Regular workspaces",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 17 },
     "yaxes": [
      { "format": "s" }
     ],
     "targets": [
      {
       "expr": "histogram_quantile(0.99, \n  sum(\n    rate(gitpod_ws_scheduler_e2e_scheduling_duration_seconds_bucket{cluster=~\"$cluster\", workspaceType=\"regular\"}[5m])\n  ) by (cluster, workspaceType, le)\n)",
       "legendFormat": "{{cluster}} - 99th percentile"
      },
      {
       "expr": "histogram_quantile(0.95, \n  sum(\n    rate(gitpod_ws_scheduler_e2e_scheduling_duration_seconds_bucket{cluster=~\"$cluster\", workspaceType=\"regular\"}[5m])\n  ) by (cluster, workspaceType, le)\n)",
       "legendFormat": "{{cluster}} - 95th percentile"
      },
      {
       "expr": "histogram_quantile(0.50, \n  sum(\n    rate(gitpod_ws_scheduler_e2e_scheduling_duration_seconds_bucket{cluster=~\"$cluster\", workspaceType=\"regular\"}[5m])\n  ) by (cluster, workspaceType, le)\n)",
       "legendFormat": "{{cluster}} - 50th percentile"
      },
      {
       "expr": "  sum(\n    rate(gitpod_ws_scheduler_e2e_scheduling_duration_seconds_sum{cluster=~\"$cluster\",workspaceType=\"regular\"}[5m])\n  ) by (cluster)\n  /\n    sum(\n    rate(gitpod_ws_scheduler_e2e_scheduling_duration_seconds_count{cluster=~\"$cluster\",workspaceType=\"regular\"}[5m])\n  ) by (cluster)",
       "legendFormat": "{{cluster}} - avg"
      }
     ]
    },
    {
     "title": "Attempts until succesful scheduling - Prebuild workspaces",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 25 },
     "yaxes": [
      { "format": "attempts" }
     ],
     "targets": [
      {
       "expr": "histogram_quantile(0.99, \n  sum(\n    rate(gitpod_ws_scheduler_pod_scheduling_attempts_bucket{cluster=~\"$cluster\", workspaceType=\"prebuild\"}[5m])\n  ) by (cluster, workspaceType, le)\n)",
       "legendFormat": "{{cluster}} - 99th percentile"
      },
      {
       "expr": "histogram_quantile(0.95, \n  sum(\n    rate(gitpod_ws_scheduler_pod_scheduling_attempts_bucket{cluster=~\"$cluster\", workspaceType=\"prebuild\"}[5m])\n  ) by (cluster, workspaceType, le)\n)",
       "legendFormat": "{{cluster}} - 95th percentile"
      },
      {
       "expr": "histogram_quantile(0.50, \n  sum(\n    rate(gitpod_ws_scheduler_pod_scheduling_attempts_bucket{cluster=~\"$cluster\", workspaceType=\"prebuild\"}[5m])\n  ) by (cluster, workspaceType, le)\n)",
       "legendFormat": "{{cluster}} - 50th percentile"
      },
      {
       "expr": "  sum(\n    rate(gitpod_ws_scheduler_pod_scheduling_attempts_bucket{cluster=~\"$cluster\",workspaceType=\"prebuild\"}[5m])\n  ) by (cluster)\n  /\n    sum(\n    rate(gitpod_ws_scheduler_pod_scheduling_attempts_bucket{cluster=~\"$cluster\",workspaceType=\"prebuild\"}[5m])\n  ) by (cluster)",
       "legendFormat": "{{cluster}} - avg"
      }
     ]
    },
    {
     "title": "End-to-end scheduling duration - Prebuild workspaces",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 25 },
     "yaxes": [
      { "format": "s" }
     ],
     "targets": [
      {
       "expr": "histogram_quantile(0.99, \n  sum(\n    rate(gitpod_ws_scheduler_e2e_scheduling_duration_seconds_bucket{cluster=~\"$cluster\", workspaceType=\"prebuild\"}[5m])\n  ) by (cluster, workspaceType, le)\n)",
       "legendFormat": "{{cluster}} - 99th percentile"
      },
      {
       "expr": "histogram_quantile(0.95, \n  sum(\n    rate(gitpod_ws_scheduler_e2e_scheduling_duration_seconds_bucket{cluster=~\"$cluster\", workspaceType=\"prebuild\"}[5m])\n  ) by (cluster, workspaceType, le)\n)",
       "legendFormat": "{{cluster}} - 95th percentile"
      },
      {
       "expr": "histogram_quantile(0.50, \n  sum(\n    rate(gitpod_ws_scheduler_e2e_scheduling_duration_seconds_bucket{cluster=~\"$cluster\", workspaceType=\"prebuild\"}[5m])\n  ) by (cluster, workspaceType, le)\n)",
       "legendFormat": "{{cluster}} - 50th percentile"
      },
      {
       "expr": "  sum(\n    rate(gitpod_ws_scheduler_e2e_scheduling_duration_seconds_sum{cluster=~\"$cluster\",workspaceType=\"prebuild\"}[5m])\n  ) by (cluster)\n  /\n    sum(\n    rate(gitpod_ws_scheduler_e2e_scheduling_duration_seconds_count{cluster=~\"$cluster\",workspaceType=\"prebuild\"}[5m])\n  ) by (cluster)",
       "legendFormat": "{{cluster}} - avg"
      }
     ]
    },
    {
     "title": "Attempts until succesful scheduling - Ghost workspaces",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 33 },
     "yaxes": [
      { "format": "attempts" }
     ],
     "targets": [
      {
       "expr": "histogram_quantile(0.99, \n  sum(\n    rate(gitpod_ws_scheduler_pod_scheduling_attempts_bucket{cluster=~\"$cluster\", workspaceType=\"ghost\"}[5m])\n  ) by (cluster, workspaceType, le)\n)",
       "legendFormat": "{{cluster}} - 99th percentile"
      },
      {
       "expr": "histogram_quantile(0.95, \n  sum(\n    rate(gitpod_ws_scheduler_pod_scheduling_attempts_bucket{cluster=~\"$cluster\", workspaceType=\"ghost\"}[5m])\n  ) by (cluster, workspaceType, le)\n)",
       "legendFormat": "{{cluster}} - 95th percentile"
      },
      {
       "expr": "histogram_quantile(0.50, \n  sum(\n    rate(gitpod_ws_scheduler_pod_scheduling_attempts_bucket{cluster=~\"$cluster\", workspaceType=\"ghost\"}[5m])\n  ) by (cluster, workspaceType, le)\n)",
       "legendFormat": "{{cluster}} - 50th percentile"
      },
      {
       "expr": "  sum(\n    rate(gitpod_ws_scheduler_pod_scheduling_attempts_bucket{cluster=~\"$cluster\",workspaceType=\"ghost\"}[5m])\n  ) by (cluster)\n  /\n    sum(\n    rate(gitpod_ws_scheduler_pod_scheduling_attempts_bucket{cluster=~\"$cluster\",workspaceType=\"ghost\"}[5m])\n  ) by (cluster)",
       "legendFormat": "{{cluster}} - avg"
      }
     ]
    },
    {
     "title": "End-to-end scheduling duration - Ghost workspaces",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 33 },
     "yaxes": [
      { "format": "s" }
     ],
     "targets": [
      {
       "expr": "histogram_quantile(0.99, \n  sum(\n    rate(gitpod_ws_scheduler_e2e_scheduling_duration_seconds_bucket{cluster=~\"$cluster\", workspaceType=\"ghost\"}[5m])\n  ) by (cluster, workspaceType, le)\n)",
       "legendFormat": "{{cluster}} - 99th percentile"
      },
      {
       "expr": "histogram_quantile(0.95, \n  sum(\n    rate(gitpod_ws_scheduler_e2e_scheduling_duration_seconds_bucket{cluster=~\"$cluster\", workspaceType=\"ghost\"}[5m])\n  ) by (cluster, workspaceType, le)\n)",
       "legendFormat": "{{cluster}} - 95th percentile"
      },
      {
       "expr": "histogram_quantile(0.50, \n  sum(\n    rate(gitpod_ws_scheduler_e2e_scheduling_duration_seconds_bucket{cluster=~\"$cluster\", workspaceType=\"ghost\"}[5m])\n  ) by (cluster, workspaceType, le)\n)",
       "legendFormat": "{{cluster}} - 50th percentile"
      },
      {
       "expr": "  sum(\n    rate(gitpod_ws_scheduler_e2e_scheduling_duration_seconds_sum{cluster=~\"$cluster\",workspaceType=\"ghost\"}[5m])\n  ) by (cluster)\n  /\n    sum(\n    rate(gitpod_ws_scheduler_e2e_scheduling_duration_seconds_count{cluster=~\"$cluster\",workspaceType=\"ghost\"}[5m])\n  ) by (cluster)",
       "legendFormat": "{{cluster}} - avg"
      }
     ]
    },
    {
     "title": "Attempts until succesful scheduling - Probe workspaces",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 41 },
     "yaxes": [
      { "format": "attempts" }
     ],
     "targets": [
      {
       "expr": "histogram_quantile(0.99, \n  sum(\n    rate(gitpod_ws_scheduler_pod_scheduling_attempts_bucket{cluster=~\"$cluster\", workspaceType=\"probe\"}[5m])\n  ) by (cluster, workspaceType, le)\n)",
       "legendFormat": "{{cluster}} - 99th percentile"
      },
      {
       "expr": "histogram_quantile(0.95, \n  sum(\n    rate(gitpod_ws_scheduler_pod_scheduling_attempts_bucket{cluster=~\"$cluster\", workspaceType=\"probe\"}[5m])\n  ) by (cluster, workspaceType, le)\n)",
       "legendFormat": "{{cluster}} - 95th percentile"
      },
      {
       "expr": "histogram_quantile(0.50, \n  sum(\n    rate(gitpod_ws_scheduler_pod_scheduling_attempts_bucket{cluster=~\"$cluster\", workspaceType=\"probe\"}[5m])\n  ) by (cluster, workspaceType, le)\n)",
       "legendFormat": "{{cluster}} - 50th percentile"
      },
      {
       "expr": "  sum(\n    rate(gitpod_ws_scheduler_pod_scheduling_attempts_bucket{cluster=~\"$cluster\",workspaceType=\"probe\"}[5m])\n  ) by (cluster)\n  /\n    sum(\n    rate(gitpod_ws_scheduler_pod_scheduling_attempts_bucket{cluster=~\"$cluster\",workspaceType=\"probe\"}[5m])\n  ) by (cluster)",
       "legendFormat": "{{cluster}} - avg"
      }
     ]
    },
    {
     "title": "End-to-end scheduling duration - Probe workspaces",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 41 },
     "yaxes": [
      { "format": "s" }
     ],
     "targets": [
      {
       "expr": "histogram_quantile(0.99, \n  sum(\n    rate(gitpod_ws_scheduler_e2e_scheduling_duration_seconds_bucket{cluster=~\"$cluster\", workspaceType=\"probe\"}[5m])\n  ) by (cluster, workspaceType, le)\n)",
       "legendFormat": "{{cluster}} - 99th percentile"
      },
      {
       "expr": "histogram_quantile(0.95, \n  sum(\n    rate(gitpod_ws_scheduler_e2e_scheduling_duration_seconds_bucket{cluster=~\"$cluster\", workspaceType=\"probe\"}[5m])\n  ) by (cluster, workspaceType, le)\n)",
       "legendFormat": "{{cluster}} - 95th percentile"
      },
      {
       "expr": "histogram_quantile(0.50, \n  sum(\n    rate(gitpod_ws_scheduler_e2e_scheduling_duration_seconds_bucket{cluster=~\"$cluster\", workspaceType=\"probe\"}[5m])\n  ) by (cluster, workspaceType, le)\n)",
       "legendFormat": "{{cluster}} - 50th percentile"
      },
      {
       "expr": "  sum(\n    rate(gitpod_ws_scheduler_e2e_scheduling_duration_seconds_sum{cluster=~\"$cluster\",workspaceType=\"probe\"}[5m])\n  ) by (cluster)\n  /\n    sum(\n    rate(gitpod_ws_scheduler_e2e_scheduling_duration_seconds_count{cluster=~\"$cluster\",workspaceType=\"probe\"}[5m])\n  ) by (cluster)",
       "legendFormat": "{{cluster}} - avg"
      }
     ]
    }
   ]
  },
  {
   "title": "Pod Metrics",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 1 },
   "collapsed": true,
   "panels": [
    {
     "title": "CPU Utilization",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 2 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(\n  rate(container_cpu_usage_seconds_total{container!=\"POD\", cluster=~\"$cluster\", node=~\"$node\", pod=~\"$pod\"}[1m])\n) by (pod, cluster, node)",
       "legendFormat": "{{cluster}} - {{node}} - {{pod}} - Cores being used"
      }
     ]
    },
    {
     "title": "CPU Saturation",
     "type": "graph",
     "description": "Saturation > 100% means that the container is requesting more than its limits.\n\nKubernetes will start to throttle CPU when that happens. That's a sign of degraded performance.\n\n'No Data' indicates that the pod has no CPU limits.",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 2 },
     "yaxes": [
      { "format": "percentunit" }
     ],
     "targets": [
      {
       "expr": "sum(\n  rate(container_cpu_usage_seconds_total{container!=\"POD\", cluster=~\"$cluster\", node=~\"$node\", pod=~\"$pod\"}[1m])\n) by (pod, cluster, node)\n/\nsum(\n  kube_pod_container_resource_limits_cpu_cores{container!=\"POD\", cluster=\"$cluster\", pod=~\"$pod\"}\n) by (pod, cluster, node)\n",
       "legendFormat": "{{cluster}} - {{node} - {{pod}} - CPU Saturation"
      },
      {
       "expr": "sum(\nrate(container_cpu_cfs_throttled_seconds_total{container!=\"POD\", cluster=~\"$cluster\", node=~\"$node\", pod=~\"$pod\"}[1m])\n) by (pod)",
       "legendFormat": "{{pod}} - CPU Throttles"
      }
     ]
    },
    {
     "title": "Memory Utilization",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 9 },
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "expr": "sum(container_memory_working_set_bytes{container!=\"POD\", cluster=~\"$cluster\", node=~\"$node\", pod=~\"$pod\"}) by (pod, cluster, node)",
       "legendFormat": "{{cluster}} - {{node}} - {{pod}}"
      }
     ]
    },
    {
     "title": "Memory Saturation",
     "type": "graph",
     "description": "Memory can't be throttled. When a container reaches 100% of its memory limits,  Kubernetes will kill the container and restart it.\n\n'No Data' indicates that the pod doesn't have Memory limits.",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 9 },
     "yaxes": [
      { "format": "percentunit" }
     ],
     "targets": [
      {
       "expr": "sum(\nrate(container_memory_working_set_bytes{container!=\"POD\", cluster=~\"$cluster\", node=~\"$node\", pod=~\"$pod\"}[1m])\n) by (pod, cluster, node)\n/\nsum(\n  kube_pod_container_resource_limits_memory_bytes{container!=\"POD\", cluster=\"$cluster\", pod=~\"$pod\"}\n) by (pod, cluster, node)\n",
       "legendFormat": "{{cluster}} - {{node}} - {{pod}} - Memory Saturation"
      }
     ]
    },
    {
     "title": "Network Utilization",
     "type": "graph",
     "gridPos": { "h": 7, "w": 8, "x": 0, "y": 16 },
     "yaxes": [
      { "format": "binBps" }
     ],
     "targets": [
      {
       "expr": "sum (\n  rate(container_network_receive_bytes_total{container!=\"POD\", cluster=~\"$cluster\", node=~\"$node\", pod=~\"$pod\"}[1m])\n) by (pod, cluster, node)",
       "legendFormat": "{{cluster}} - {{node}} - {{pod}} - Received"
      },
      {
       "expr": "sum (\n  rate(container_network_transmit_bytes_total{container!=\"POD\", cluster=~\"$cluster\", node=~\"$node\", pod=~\"$pod\"}[1m])\n) by (pod, cluster, node)",
       "legendFormat": "{{cluster}} - {{node}} - {{pod}} - Transmitted"
      }
     ]
    },
    {
     "title": "Network Saturation (Packets Dropped)",
     "type": "graph",
     "gridPos": { "h": 7, "w": 8, "x": 8, "y": 16 },
     "yaxes": [
      { "format": "pps" }
     ],
     "targets": [
      {
       "expr": "sum (\n  rate(container_network_receive_packets_dropped_total{container!=\"POD\", pod!=\"\", cluster=~\"$cluster\", node=~\"$node\", pod=~\"$pod\"}[1m])\n) by (pod, cluster, node)",
       "legendFormat": "{{cluster}} - {{node}} - {{pod}} - Receive"
      },
      {
       "expr": "sum (\n  rate(container_network_transmit_packets_dropped_total{container!=\"POD\", pod!=\"\", cluster=~\"$cluster\", node=~\"$node\", pod=~\"$pod\"}[1m])\n) by (pod, cluster, node)",
       "legendFormat": "{{cluster}} - {{node}} - {{pod}} - Transmit"
      }
     ]
    },
    {
     "title": "Network Errors",
     "type": "graph",
     "gridPos": { "h": 7, "w": 8, "x": 16, "y": 16 },
     "yaxes": [
      { "format": "Errors/s" }
     ],
     "targets": [
      {
       "expr": "sum (\n  rate(container_network_receive_errors_total{container!=\"POD\", pod!=\"\", cluster=~\"$cluster\", node=~\"$node\", pod=~\"$pod\"}[1m])\n) by (pod, cluster, node)",
       "legendFormat": "{{cluster}} - {{node}} - {{pod}} - Received"
      },
      {
       "expr": "sum (\n  rate(container_network_transmit_errors_total{container!=\"POD\", pod!=\"\", cluster=~\"$cluster\", node=~\"$node\", pod=~\"$pod\"}[1m])\n) by (pod, cluster, node)",
       "legendFormat": "{{cluster}} - {{node}} - {{pod}} - Transmitted"
      }
     ]
    },
    {
     "title": "Pod Restarts",
     "type": "graph",
     "gridPos": { "h": 9, "w": 8, "x": 0, "y": 23 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "rate(kube_pod_container_status_restarts_total{cluster=~\"$cluster\", pod=~\"$pod\"}[1m])",
       "legendFormat": "{{cluster}} - {{kubernetes_pod_node_name}} - {{pod}} "
      }
     ]
    },
    {
     "title": "Pod Status",
     "type": "graph",
     "gridPos": { "h": 9, "w": 8, "x": 8, "y": 23 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "kube_pod_container_status_running{cluster=~\"$cluster\", pod=~\"$pod\"} == 1 ",
       "legendFormat": "{{pod}}  - RUNNING"
      },
      {
       "expr": "(\n  sum by (pod) (kube_pod_container_status_terminated{cluster=~\"$cluster\", pod=~\"$pod\"}) == 1\n) * on(pod) group_left(reason) (\n  sum by (pod, reason) (kube_pod_container_status_terminated_reason{cluster=~\"$cluster\", pod=~\"$pod\"}) == 1\n)",
       "legendFormat": "{{pod}}  - TERMINATED -> {{reason}}"
      },
      {
       "expr": "(\n  sum by (pod) (kube_pod_container_status_waiting{cluster=~\"$cluster\", pod=~\"$pod\"}) == 1\n) * on(pod) group_left(reason) (\n  sum by (pod, reason) (kube_pod_container_status_waiting_reason{cluster=~\"$cluster\", pod=~\"$pod\"}) == 1\n)",
       "legendFormat": "{{pod}}  - WAITING -> {{reason}}"
      }
     ]
    },
    {
     "title": "Replicas availability",
     "type": "graph",
     "gridPos": { "h": 9, "w": 8, "x": 16, "y": 23 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "kube_deployment_spec_replicas{cluster=~\"$cluster\", deployment=\"ws-scheduler\"}",
       "legendFormat": "{{cluster}} - {{deployment}} - Desired"
      },
      {
       "expr": "kube_deployment_status_replicas_available{cluster=~\"$cluster\", deployment=\"ws-scheduler\"}",
       "legendFormat": "{{cluster}} - {{deployment}} - Available replicas"
      },
      {
       "expr": "kube_deployment_status_replicas_unavailable{cluster=~\"$cluster\", deployment=\"ws-scheduler\"}",
       "legendFormat": "{{cluster}} - {{deployment}} - Unvailable replicas"
      }
     ]
    }
   ]
  }
 ]
}