{
 "title": "Gitpod / SLOs / Policy",
 "tags": [ "gitpod-mixin" ],
 "time": { "from": "now-12h", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   { "name": "datasource", "query": "prometheus" },
   {
    "name": "cluster",
    "query": {
     "query": "label_values(gitpod_agent_smith_discovered_workspaces_total, cluster)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "SLO and Error budget",
   "type": "stat",
   "gridPos": { "h": 4, "w": 11, "x": 7, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    { "expr": "0.95", "legendFormat": "Availability target" },
    {
     "expr": "(1 - \n  (\n    1 - (\r\n          sum(rate(gitpod_agent_smith_discovered_workspaces_total[5m]))\r\n          /\r\n          sum(rate(gitpod_agent_smith_policed_workspaces_total[5m]))\r\n        )\n  )\n) - 0.95",
     "legendFormat": "Monthly error budget remaining"
    }
   ]
  },
  { "title": "Burn ratios", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 4 } },
  {
   "title": "Unpoliced workspaces ratio",
   "type": "graph",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 5 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "1 - (\n  sum(rate(gitpod_agent_smith_discovered_workspaces_total[5m]))\n  /\n  sum(rate(gitpod_agent_smith_policed_workspaces_total[5m]))\n)",
     "legendFormat": "5m failure ratio"
    },
    {
     "expr": "1 - (\n  sum(rate(gitpod_agent_smith_discovered_workspaces_total[30m]))\n  /\n  sum(rate(gitpod_agent_smith_policed_workspaces_total[30m]))\n)",
     "legendFormat": "30m failure ratio"
    },
    {
     "expr": "1 - (\n  sum(rate(gitpod_agent_smith_discovered_workspaces_total[1h]))\n  /\n  sum(rate(gitpod_agent_smith_policed_workspaces_total[1h]))\n)",
     "legendFormat": "1h failure ratio"
    },
    {
     "expr": "1 - (\n  sum(rate(gitpod_agent_smith_discovered_workspaces_total[2h]))\n  /\n  sum(rate(gitpod_agent_smith_policed_workspaces_total[2h]))\n)",
     "legendFormat": "2h failure ratio"
    },
    {
     "expr": "1 - (\n  sum(rate(gitpod_agent_smith_discovered_workspaces_total[6h]))\n  /\n  sum(rate(gitpod_agent_smith_policed_workspaces_total[6h]))\n)",
     "legendFormat": "6h failure ratio"
    },
    {
     "expr": "1 - (\n  sum(rate(gitpod_agent_smith_discovered_workspaces_total[1d]))\n  /\n  sum(rate(gitpod_agent_smith_policed_workspaces_total[1d]))\n)",
     "legendFormat": "1d failure ratio"
    },
    {
     "expr": "1 - (\n  sum(rate(gitpod_agent_smith_discovered_workspaces_total[3d]))\n  /\n  sum(rate(gitpod_agent_smith_policed_workspaces_total[3d]))\n)",
     "legendFormat": "3d failure ratio"
    },
    {
     "expr": "1 - (\n  sum(rate(gitpod_agent_smith_discovered_workspaces_total[30d]))\n  /\n  sum(rate(gitpod_agent_smith_policed_workspaces_total[30d]))\n)",
     "legendFormat": "30d failure ratio"
    },
    { "expr": "0.05", "legendFormat": "Failure ratio threshold" }
   ]
  },
  {
   "title": "$cluster: Unpoliced workspaces ratio",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 11 },
   "repeat": "cluster",
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "1 - (\n  sum(rate(gitpod_agent_smith_discovered_workspaces_total{cluster=~\"$cluster\"}[5m]))\n  /\n  sum(rate(gitpod_agent_smith_policed_workspaces_total{cluster=~\"$cluster\"}[5m]))\n)",
     "legendFormat": "5m failure ratio"
    },
    {
     "expr": "1 - (\n  sum(rate(gitpod_agent_smith_discovered_workspaces_total{cluster=~\"$cluster\"}[30m]))\n  /\n  sum(rate(gitpod_agent_smith_policed_workspaces_total{cluster=~\"$cluster\"}[30m]))\n)",
     "legendFormat": "30m failure ratio"
    },
    {
     "expr": "1 - (\n  sum(rate(gitpod_agent_smith_discovered_workspaces_total{cluster=~\"$cluster\"}[1h]))\n  /\n  sum(rate(gitpod_agent_smith_policed_workspaces_total{cluster=~\"$cluster\"}[1h]))\n)",
     "legendFormat": "1h failure ratio"
    },
    {
     "expr": "1 - (\n  sum(rate(gitpod_agent_smith_discovered_workspaces_total{cluster=~\"$cluster\"}[2h]))\n  /\n  sum(rate(gitpod_agent_smith_policed_workspaces_total{cluster=~\"$cluster\"}[2h]))\n)",
     "legendFormat": "2h failure ratio"
    },
    {
     "expr": "1 - (\n  sum(rate(gitpod_agent_smith_discovered_workspaces_total{cluster=~\"$cluster\"}[6h]))\n  /\n  sum(rate(gitpod_agent_smith_policed_workspaces_total{cluster=~\"$cluster\"}[6h]))\n)",
     "legendFormat": "6h failure ratio"
    },
    {
     "expr": "1 - (\n  sum(rate(gitpod_agent_smith_discovered_workspaces_total{cluster=~\"$cluster\"}[1d]))\n  /\n  sum(rate(gitpod_agent_smith_policed_workspaces_total{cluster=~\"$cluster\"}[1d]))\n)",
     "legendFormat": "1d failure ratio"
    },
    {
     "expr": "1 - (\n  sum(rate(gitpod_agent_smith_discovered_workspaces_total{cluster=~\"$cluster\"}[3d]))\n  /\n  sum(rate(gitpod_agent_smith_policed_workspaces_total{cluster=~\"$cluster\"}[3d]))\n)",
     "legendFormat": "3d failure ratio"
    },
    {
     "expr": "1 - (\n  sum(rate(gitpod_agent_smith_discovered_workspaces_total{cluster=~\"$cluster\"}[30d]))\n  /\n  sum(rate(gitpod_agent_smith_policed_workspaces_total{cluster=~\"$cluster\"}[30d]))\n)",
     "legendFormat": "30d failure ratio"
    },
    { "expr": "0.05", "legendFormat": "Failure ratio threshold" }
   ]
  }
 ]
}